# Generated by Django 6.1 on 2026-08-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('organization_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('scan_type', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('record_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extraction Job',
                'verbose_name_plural': 'Extraction Jobs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PipelineMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(default='hubspot_deals_pipeline', max_length=255)),
                ('destination_type', models.CharField(default='postgresql', max_length=255)),
                ('active_scanners', models.IntegerField(default=1)),
                ('total_extractions', models.IntegerField(default=0)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('stage', models.CharField(blank=True, default='appointmentscheduled', max_length=255)),
                ('pipeline', models.CharField(blank=True, default='default', max_length=255)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_records', to='api.extractionjob')),
            ],
            options={
                'verbose_name': 'Deal Record',
                'verbose_name_plural': 'Deal Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
