# Generated by Django 6.1 on 2026-08-23 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealrecord',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Deal Record', 'verbose_name_plural': 'Deal Records'},
        ),
        migrations.AddField(
            model_name='dealrecord',
            name='_extracted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dealrecord',
            name='_scan_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dealrecord',
            name='_tenant_id',
            field=models.CharField(blank=True, db_index=True, default='default-tenant', max_length=255),
        ),
    ]
