# Generated by Django 6.1 on 2026-08-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dealrecord_options_dealrecord__extracted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionjob',
            name='checkpoint_data',
            field=models.JSONField(blank=True, default=dict, help_text='Checkpoint state metadata'),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='last_cursor',
            field=models.CharField(blank=True, help_text='Cursor token for pagination checkpointing', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='pages_processed',
            field=models.IntegerField(default=0, help_text='Total pages fetched during extraction'),
        ),
        migrations.AlterField(
            model_name='extractionjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
